#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$SCRIPT_DIR/asn1c_code"
cd "$SCRIPT_DIR/asn1c_code"
../../asn1c/asn1c/asn1c -fcompound-names -S ../../asn1c/skeletons ../J3287_ASN_flat/*.asn
cd "$SCRIPT_DIR"

# ── Post-process: fix IOC CLASS alias files ──────────────────────────────────
# asn1c generates invalid C syntax for CLASS aliases (C-ASR-EV, etc.) because
# C-2ENT is an IOC CLASS with no wire encoding.  Replace with ANY-based stubs.

# 1. Install handwritten stubs (not generated by asn1c)
cp "$SCRIPT_DIR/stubs/C-2ENT.h"      "$SCRIPT_DIR/asn1c_code/C-2ENT.h"
cp "$SCRIPT_DIR/stubs/C-2ENT.c"      "$SCRIPT_DIR/asn1c_code/C-2ENT.c"
cp "$SCRIPT_DIR/stubs/decode_shim.h" "$SCRIPT_DIR/asn1c_code/decode_shim.h"
cp "$SCRIPT_DIR/stubs/decode_shim.c" "$SCRIPT_DIR/asn1c_code/decode_shim.c"

# 2. Fix the four broken alias .c files:
#    &asn_OP_struct C_2ENT  →  &asn_OP_ANY
#    struct C_2ENT_constraint  →  C_2ENT_constraint
for f in C-ASR-EV C-ASR-OBS-BY-TGT C-ASR-SINGLE-OBS C-OBS-PDU; do
    sed -i \
        -e 's/&asn_OP_struct C_2ENT,/\&asn_OP_ANY,/' \
        -e 's/\bstruct C_2ENT_constraint\b/C_2ENT_constraint/' \
        "$SCRIPT_DIR/asn1c_code/$f.c"
done
echo "Post-processing complete."
