#ifndef DECODE_SHIM_H
#define DECODE_SHIM_H

#include <stddef.h>
#include <asn_application.h>

/*
 * PDU dispatch table entry.
 * Defined in pdu_table.c (auto-generated by build.sh).
 */
typedef struct {
    const char            *name;  /* C identifier (hyphens → underscores) */
    asn_TYPE_descriptor_t *td;
} pdu_entry_t;

extern pdu_entry_t pdu_table[];

/*
 * Decode OER/COER bytes as the named PDU type, returning a JER (JSON) string.
 *
 * pdu_name  : C identifier of the PDU (hyphens replaced with underscores)
 * data      : raw COER bytes
 * data_len  : byte count
 * json_out  : on success, set to a malloc'd NUL-terminated JSON string;
 *             caller must free with free_buffer()
 * err_buf   : on failure, filled with a NUL-terminated error description
 * err_size  : capacity of err_buf
 *
 * Returns 0 on success, -1 on failure.
 */
int decode_oer_to_jer(
    const char *pdu_name,
    const void *data, size_t data_len,
    char      **json_out,
    char       *err_buf, size_t err_size);

/*
 * Encode a JER (JSON) string as the named PDU type, returning OER/COER bytes.
 *
 * pdu_name  : C identifier of the PDU (hyphens replaced with underscores)
 * json_in   : NUL-terminated JER JSON string
 * oer_out   : on success, set to a malloc'd byte buffer;
 *             caller must free with free_buffer()
 * oer_len   : on success, set to the number of bytes in *oer_out
 * err_buf   : on failure, filled with a NUL-terminated error description
 * err_size  : capacity of err_buf
 *
 * Returns 0 on success, -1 on failure.
 */
int encode_jer_to_oer(
    const char *pdu_name,
    const char *json_in,
    void      **oer_out,
    size_t     *oer_len,
    char       *err_buf, size_t err_size);

/* Free a buffer previously returned by decode_oer_to_jer or encode_jer_to_oer. */
void free_buffer(void *ptr);

#endif /* DECODE_SHIM_H */
